### ISSUE TITLE
Reminder doesn't do anything

### ISSUE THREAD

**Issue by ChristopherKing42** [drmercer/Ponderizer#39]
I have the reminder set, but it doesn't produce any type of reminder or notification.

**Comment by drmercer** [comment]
@ChristopherKing42: Currently the reminder code is broken. For one thing, it doesn't persist past a reboot. When the device reboots, the reminder trigger is unset by the system, and the app doesn't (but should) re-set the reminder trigger. I've made a fix and will include it in the next update.

**Comment by drmercer** [comment]
This has been fixed by the most recent update, version 3.0. Thanks for your feedback!
